create sequence hibernate_sequence start with 1 increment by 1;


create table book (id bigint generated by default as identity, course varchar(512) not null, title varchar(1024) not null, primary key (id));
create table book_authors (book_id bigint not null, authors varchar(255));
create table book_sellers (book_id bigint not null, sellers_email varchar(255) not null);
create table message (id bigint generated by default as identity, text varchar(255), receiver_email varchar(255) not null, sender_email varchar(255) not null, primary key (id));
create table users (email varchar(255) not null, enabled boolean not null, name varchar(255) not null, password varchar(255) not null, surname varchar(255) not null, primary key (email));
alter table book add constraint UK_cknphubg9grmv8epxis6xqi1 unique (course);
alter table book add constraint UK_g0286ag1dlt4473st1ugemd0m unique (title);
alter table book_authors add constraint FKs4xm7q8i3uxvaiswj1c35nnxw foreign key (book_id) references book;
alter table book_sellers add constraint FKc4w7cyfffg6l814ud6inld4p9 foreign key (sellers_email) references users;
alter table book_sellers add constraint FKkmpxn70jr7stgmufer2lfsafp foreign key (book_id) references book;
alter table message add constraint FKb944tffcq8o8omuojf97q7es9 foreign key (receiver_email) references users;
alter table message add constraint FKuqfakq269q9cbhdcdevk7a90 foreign key (sender_email) references users;


